services:
  # Service pour le backend PHP (Symfony)
  php:
    build:
      context: ./backend
      dockerfile: ../Docker/PHP/Dockerfile
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - database
    networks:
      - app-network

  # Service Nginx pour le backend
  nginx:
    image: nginx:alpine
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - app-network

  # Service pour le frontend Angular (front_coaching)
  angular:
    build:
      context: .
      dockerfile: ./Docker/Angular/Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

  # Service pour la base de données
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
